name: aws_common
description: Common types and utilities used across AWS and Amplify packages.
version: 0.4.2+4
homepage: https://docs.amplify.aws/lib/q/platform/flutter/
repository: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/aws_common
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: ">=3.1.0-49.0.dev <4.0.0"

dependencies:
  async: ^2.10.0
  built_collection: ^5.0.0
  built_value: ">=8.5.0 <8.6.0"
  collection: ^1.15.0
  http2: ^2.0.0
  json_annotation: ">=4.8.0 <4.9.0"
  logging: ^1.0.0
  meta: ^1.7.0
  mime: ^1.0.0
  os_detect: ^2.0.0
  path: ^1.8.0
  stream_transform: ^2.0.0
  uuid: ">=3.0.6 <=3.0.7"
  web: ^0.1.0-beta

dependency_overrides:
  test:
    git:
      url: https://github.com/dart-lang/test/
      path: pkgs/test
  test_api:
    git:
      url: https://github.com/dart-lang/test/
      path: pkgs/test_api
  test_core:
    git:
      url: https://github.com/dart-lang/test/
      path: pkgs/test_core

dev_dependencies:
  amplify_lints: ">=2.0.3 <2.1.0"
  build_runner: ^2.4.0
  build_test: ^2.1.5
  build_web_compilers: ^4.0.0
  built_value_generator: 8.5.0
  json_serializable: 6.6.1
  stream_channel: ^2.1.0
  test:
    git:
      url: https://github.com/dart-lang/test/
      path: pkgs/test
